const photosInfo = [
  {
    id: "1",
    imgSrc: "photoImg1",
    category: "Paisajes",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "2",
    imgSrc: "photoImg2",
    category: "Animales",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "3",
    imgSrc: "photoImg3",
    category: "Animales",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "4",
    imgSrc: "photoImg4",
    category: "Animales",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "5",
    imgSrc: "photoImg5",
    category: "Animales",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "6",
    imgSrc: "photoImg1",
    category: "Animales",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "7",
    imgSrc: "photoImg3",
    category: "Paisajes",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "8",
    imgSrc: "photoImg5",
    category: "Paisajes",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "9",
    imgSrc: "photoImg4",
    category: "Paisajes",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "10",
    imgSrc: "photoImg1",
    category: "Paisajes",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
  {
    id: "11",
    imgSrc: "photoImg5",
    category: "Paisajes",
    imgDownload: "https://i.postimg.cc/mrPJyQDt/g2.jpg",
    description: "Foto",
  },
];

export default photosInfo;
