const videosInfoAll = [
  {
    titulo: "Dirección y producción",
    des: "Corto Dar el primer paso",
    data: ["2022", "1:01 min"],
    video: "Corto",
    poster: "PosterCorto",
    youtube: "#",
  },
  {
    titulo: "Matizando Ana Sanz",
    des: "Vídeo práctica, ejercicio realizado en el programa Adobe After Efects.",
    data: ["2022", "0:24 min", "Lyrics"],
    video: "Matizando",
    poster: "PosterMatizando",
    youtube: "https://www.youtube.com/watch?v=YzH9c27Hhpw",
  },
  {
    titulo: "Invitación Documental",
    des: "Ejercicio Croma y rastreador AE",
    data: ["2022", "5:06 min"],
    video: "Invitacion",
    poster: "PosterInvitacion",
    youtube: "https://www.youtube.com/watch?v=GEP9KE5rA50",
  },
  {
    titulo: "Documental En Conflicto",
    des: "Primer capitulo de Documental En Conflicto, Espectativas",
    data: ["2022", "0:31 min"],
    video: "Documental",
    poster: "PosterDocumental",
    youtube: "https://www.youtube.com/watch?v=eFZlIap-5Yg",
  },
  {
    titulo: "Edición - Reel Honda la estrella",
    des: "Edición para Motocicletas Honda",
    data: ["2023", "1:07 min"],
    video: "Edicion",
    poster: "PosterEdicion",
    youtube: "#",
  },
  {
    titulo: "Edición y animación",
    des: "Animación -Invitación Campaña Voces a Voces Noble",
    data: ["2023", "1:00 min"],
    video: "Avoces",
    poster: "PosterAvoces",
    youtube: "#",
  },
  {
    titulo: "Animación",
    des: "Campaña Liga Espacial, Rocket Planet Agencias Noble",
    data: ["2023", "0:21 min"],
    video: "Animacion",
    poster: "PosterAnimacion",
    youtube: "#",
  },
  {
    titulo: "Animación",
    des: "Campaña Liga Espacial, Rocket Planet Agencias Noble",
    data: ["2023", "0:19 min"],
    video: "Ranking",
    poster: "PosterRanking",
    youtube: "#",
  },
  {
    titulo: "Producción y edición",
    des: "Día de la mujer Noble",
    data: ["2023", "1:09 min"],
    video: "Mujer",
    poster: "PosterMujer",
    youtube: "#",
  },
  {
    titulo: "Producción y edición",
    des: "Publicidad Campaña FINO Company",
    data: ["2023", "1:39 min"],
    video: "Produccion",
    poster: "PosterProduccion",
    youtube: "#",
  },
];

export default videosInfoAll;
