const videosInfoAll = [
  {
    titulo: "Dirección y producción",
    des: "Corto Dar el primer paso",
    data: ["Marzo 2022", "1:01 min"],
    video: "Corto",
    poster: "PosterCorto",
    youtube: "#",
  },
  {
    titulo: "Animación",
    des: "Matizando Ana Sanz Video - Lyrics",
    data: ["Octubre 2022", "3:34 min", "Lyrics"],
    video: "Matizando",
    poster: "PosterMatizando",
    youtube: "https://www.youtube.com/watch?v=YzH9c27Hhpw",
  },
  {
    titulo: "Animación y edición",
    des: "Invitación Documental En Conflicto",
    data: ["Diciembre 2022", "0:30 min"],
    video: "Invitacion",
    poster: "PosterInvitacion",
    youtube: "https://www.youtube.com/watch?v=GEP9KE5rA50",
  },
  {
    titulo: "Animación y dirección de arte",
    des: "Documental En Conflicto",
    data: ["Diciembre 2022", "5:06 min"],
    video: "Documental",
    poster: "PosterDocumental",
    youtube: "https://www.youtube.com/watch?v=eFZlIap-5Yg",
  },
  {
    titulo: "Edición",
    des: "Reel para Marca Honda la estrella, Agencias Noble",
    data: ["Febrero 2023", "1:07 min"],
    video: "Edicion",
    poster: "PosterEdicion",
    youtube: "#",
  },
  {
    titulo: "Edición y animación",
    des: "Invitación Campaña Voces a Voces Noble",
    data: ["Marzo 2023", "1:00 min"],
    video: "Avoces",
    poster: "PosterAvoces",
    youtube: "#",
  },
  {
    titulo: "Animación",
    des: "Campaña Liga Espacial, Rocket Planet Agencias Noble",
    data: ["Marzo 2023", "0:21 min"],
    video: "Animacion",
    poster: "PosterAnimacion",
    youtube: "#",
  },
  {
    titulo: "Animación ",
    des: "Campaña Liga Espacial, Rocket Planet, Agencias Noble",
    data: ["Marzo 2023", "0:19 min"],
    video: "Ranking",
    poster: "PosterRanking",
    youtube: "#",
  },
  {
    titulo: "Producción y edición",
    des: "Día de la mujer Noble",
    data: ["Marzo 2023", "1:09 min"],
    video: "Mujer",
    poster: "PosterMujer",
    youtube: "#",
  },
  {
    titulo: "Producción, animación y edición",
    des: "Publicidad Campaña FINO Services",
    data: ["Abril 2023", "1:39 min"],
    video: "Produccion",
    poster: "PosterProduccion",
    youtube: "#",
  },
  {
    titulo: "Edición",
    des: "Publicidad Campaña FINO Services",
    data: ["Abril 2023", "1:39 min"],
    video: "Fino",
    poster: "PosterFino",
    youtube: "#",
  },
];

export default videosInfoAll;
